### ISSUE TITLE
Backlog

### ISSUE THREAD

**Issue by imranesarsri** [labs-web/lab-deploy-laravel#11]
# Backlog
## Travail à faire 

1. Liste des tâches 
2. Validation de la liste des tâches avec le formateur
3. Création des fichiers de description des tâches
4. Validation avec le formateur 
5. Création des issues 
6. Changement des numéro des issues sur vs code
  - Changement les noms des fichier dans le dossier backlog :
    - priorité +'.'+ le nom de tache +'.'+  numero de l'issue +'.md'

**Comment by husseinbouik** [comment]
- Livrable non valide
