### ISSUE TITLE
Init-lab

### ISSUE THREAD

**Issue by imranesarsri** [labs-web/lab-deploy-laravel#36]
# Init rapport

## Travail à faire
- changement des noms des issues

## Livrable
- docs/*

**Comment by essarraj-fouad** [comment]
- la description de la tâche n'est pas valide
  - Le livrable n'est pas valide

**Comment by zaani12** [comment]
- la description de la tâche n'est pas valide

**Comment by husseinbouik** [comment]
- le résultat n'est pas conforme au livrables dans la description de l'issue
