### ISSUE TITLE
Fix-init-rapport-init-presentation

### ISSUE THREAD

**Issue by imranesarsri** [labs-web/lab-deploy-laravel#38]
# Fix Init rapport et Init présentation

## Travail à faire 
Création d'une rapport et présentation sans contenu, mais avec les titres des diapositives
## Livrable 
- docs/* : je vais modifier tous les fichier dans cette repertoire
- presentation.md
- index.md
- Readme.json : je vais ajouter seleument le lien de presentation
- Readme.md  : je vais ajouter seleument le lien de presentation

**Comment by essarraj-fouad** [comment]
- la description de la tâche n'est pas valide
  - Le livrable n'est pas valide

**Comment by husseinbouik** [comment]
- le résultat n'est pas conforme au livrables dans la description de l'issue
